name = "hex-real-roots"
defaultTargets = ["HexRealRoots"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "0166cc099045e0366efd6a152f633c9e9baf0550"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "591c146eeee0ef301a110cd33c19cc0cf1e07352"

[[lean_lib]]
name = "HexRealRoots"

[[lean_lib]]
name = "HexRealRootsTests"
globs = ["HexRealRoots.ReplayTest"]
