name = "hex-real-roots"
defaultTargets = ["HexRealRoots"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "90b63463fe66286baf70e8c6594efc2f202aee03"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "6ad58796dca6bae4936003412816e4e844055558"

[[lean_lib]]
name = "HexRealRoots"

[[lean_lib]]
name = "HexRealRootsTests"
globs = ["HexRealRoots.ReplayTest"]
