name = "hex-real-roots"
defaultTargets = ["HexRealRoots"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "385df1df6b2667aeb001b6b781f7109943de243b"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a47240943e925951a676d1a1c2f2a615ae68fdef"

[[lean_lib]]
name = "HexRealRoots"

[[lean_lib]]
name = "HexRealRootsTests"
globs = ["HexRealRoots.ReplayTest"]
